language: node_js
node_js:
  - "stable"

branches:
  only:
    - master
    - dev

stages:
  - name: deploy
    # require the branch name to be master and that we are trying to merge into master
    if: (branch = master AND type = push) OR (branch = dev AND type = push)
    

script:
  - echo "hello"
  - if [ $TRAVIS_BRANCH == "master" ]; then echo "master"; fi
  - if [ $TRAVIS_BRANCH == "dev" ]; then echo "dev"; fi

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - export BRANCH=$(if [ "$BRANCH" == "master" ]; then echo "prod"; else echo $BRANCH; fi)
  - echo "pushing to env:$BRANCH"
  - echo "yupi!"